### ISSUE TITLE
Allow Players to Change Bot’s Bodygroups and Skins

### ISSUE THREAD

**Issue by T-Rizzle12** [T-Rizzle12/Custom-Gmod-Bot#31]
Suggestion by Enviyon on steam
Suggestion: Can you add feature to change bodygroups in bots.

# Todo
- [x] Allow players to set the bot’s bodygroup 
- [x] Allow players to set the bot’s skin
- [x] Add fail safes to prevent the addon from sending errors to the player

**Comment by T-Rizzle12** [comment]
#30 I haven’t forgotten about this. As soon as my computer is working again. I will begin work on this.

**Comment by T-Rizzle12** [comment]
Added in #30
